steps:

  - id: limitbuildcheck
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
    - -c
    - |
      export parallelbuild=$(gcloud builds list --region=us-central1 --filter="substitutions.TRIGGER_NAME=$TRIGGER_NAME AND status=WORKING" --format="value(status)" | wc -l)        
      export approvebuild=$(gcloud builds list --region=us-central1 --format="value(status)" --filter="substitutions.TRIGGER_NAME='prodbuild' AND status='PENDING'" | wc -l)
      if [ $parallelbuild -gt 1 ]
      then
        echo "parallel build running. This may corrupt the exported files in GCS location"
        exit 1
      else
        echo "Proceeding. No other parallel export build"  
      fi
      if [ $approvebuild -gt 0 ]
      then
        echo "some other build waiting for approval"
        exit 1
      else
        echo "Proceeding. No builds waiting for approval"  
      fi

  - id: fetchuser
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo $BUILD_ID
        export buildhere=$BUILD_ID
        export trigid=$(gcloud builds describe $BUILD_ID --region=us-central1 --format="value(buildTriggerId)")
        sed -i "s/triggerhere/$trigid/g" export/trigger.sh
        chmod 777 export/trigger.sh
        export w1=$(export/trigger.sh)
        export w2=$(echo $w1 | cut -d " " -f2)
        export runnerid=$w2
        export runnername=$(echo $runnerid | cut -d '@' -f 1)
        echo $buildhere
        echo $runnerid
        echo $runnername
        pwd
        ls
        echo $runnername > ./runnername.txt
        echo $runnerid > ./runnerid.txt

        
  - id: Exportgcs
    name: 'python:3.10'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      pip3 install -r export/requirements.txt
      export runnerid=$(cat runnerid.txt)
      python3 export/export.py ${_USERCOMMITMESSAGE} $runnerid

  - id: downloadartifacts
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
    - -c
    - |
      apt-get update && apt-get install -y jq
      export agent_name=$(jq -r .agent_name config.json)
      export bucket_name=$(jq -r .bucket config.json)
      echo $agent_name
      echo $bucket_name
      mkdir agenttemp
      gsutil cp "gs://$bucket_name/exports/dev/$agent_name" agenttemp/$agent_name
      gsutil cp "gs://$bucket_name/exports/dev/${agent_name}_metadata.json" agenttemp/metadata.json

  - id: csrcheckin
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
    - -c
    - |
      export runnerid=$(cat runnerid.txt)
      export runnername=$(cat runnername.txt)
      chmod 777 export/repopush.sh
      export/repopush.sh ${_USERCOMMITMESSAGE} $runnername $runnerid

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true