
# just fix selected whitespace
autofix-min-whitespace:
	autopep8 --select W291,E302,E301 --in-place *py

# fix all default whitespace issues in place
autofix-all-ws:
	autopep8 --aggressive --aggressive dfcx.py --verbose --in-place

